version: "3.9"
services:
  app:
    image: node:18
    volumes:
      - ./server:/usr/src
    working_dir: /usr/src
    ports:
      - 3000:3000
    command: >
      /bin/sh -c `      
        npm install &&
        npm run serve
      `
