openapi: "3.0.2"
info:
  title: Login API
  version: "1.0"
servers:
  - url: https//localhost:3000
paths:
  /login:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                example:
                  name: Me
        "404":
          description: Fail
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: user not found
